# Generated by Django 4.0.6 on 2022-07-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_presetpack_path_alter_samplepack_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presetpack',
            name='path',
            field=models.FileField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='samplepack',
            name='path',
            field=models.FileField(blank=True, upload_to=None),
        ),
    ]
