# Generated by Django 4.0.6 on 2022-07-19 21:40

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_presetpack_example_samplepack_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presetpack',
            name='example',
            field=models.FileField(blank=True, upload_to=base.models.wrapper),
        ),
        migrations.AlterField(
            model_name='samplepack',
            name='example',
            field=models.FileField(blank=True, upload_to=base.models.wrapper),
        ),
    ]
